- name: simple block example
  hosts: all
  tasks:
    - name: setting up http
      block:
      - name: installing http
        yum:
          name: http
          state: present
      - name: restart httpd
        service:
          name: httpd
          state: started
      when: ansible_distribution == "CentOS"
